import cgi
print("content-text:text/html\r\n\r\n")
print("<html>")
print("<form action=AdminChkLogin.py>")
print("<center>")
print("<table border=1>")
print("<caption><font size=7> Admin Login Form</font></caption>")
print("<tr><td>Admin id</td><td><input type= text name=aid></td></tr>")
print("<tr><td>Admin Password</td><td><input type= password name=apass></td></tr>")
print("<tr><td><input type=submit name=Login></td><td><input type=reset></td></tr>")
print("</table>")
print("</center>")
print("</form>")
print("</html>")
